__version__ = '1.0.13'
__author__ = 'Forcepoint'
__description__ = 'Python based API to Forcepoint NGFW Management Center'
__url__ = 'http://github.com/Forcepoint/fp-NGFW-SMC-python'
__author_email__ = 'PSIRT@forcepoint.com'
__license__ = 'Apache 2.0'
