__version__ = '0.7.0-b16'
__author__ = 'Forcepoint'
__description__ = 'Python based API to Forcepoint NGFW Management Center'
__url__ = 'http://github.com/Forcepoint/smc-python'
__author_email__ = 'PSIRT@forcepoint.com'
__license__ = 'Apache 2.0'
